sudo: false
language: python
python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5
script:
  - if [[ $TRAVIS_PYTHON_VERSION == 2* ]]; then pip install pylint requests beautifulsoup4; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 3* ]]; then pip3 install pylint requests beautifulsoup4; fi
  - pylint src
