sudo: false
language: python
python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5
script:
  - if [[ $TRAVIS_PYTHON_VERSION == 2* ]]; then pip install pylint; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 3* ]]; then pip3 install pylint; fi
  - pylint src/__main__.py src/main.py src/functions.py src/confirm.py
